// <auto-generated />
using System;
using FinanceCalc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceCalc.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030213359_AddOfferDateField")]
    partial class AddOfferDateField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceCalc.Domain.Entities.BondEntity", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CapitalProfitability")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal>("CapitalProfitabilityYear")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<decimal?>("Coupon")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<decimal?>("CouponProfitability")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal?>("CouponProfitabilityYear")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<int?>("CouponsPerYear")
                        .HasColumnType("integer");

                    b.Property<double?>("CouponsPeriodMonths")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationYears")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<DateTime?>("OfferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProfitabilityYear")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.HasKey("Ticker", "DateStart");

                    b.ToTable("Bonds", (string)null);
                });

            modelBuilder.Entity("FinanceCalc.Domain.Entities.BondMetricsEntity", b =>
                {
                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CostDiffDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CouponYieldYearDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DurationYearsDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MeanCostDiffPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanCouponYieldYear")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanDurationYears")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanTotalYieldYear")
                        .HasColumnType("double precision");

                    b.Property<double>("StdErrorCostDiffPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("StdErrorCouponYieldYear")
                        .HasColumnType("double precision");

                    b.Property<double>("StdErrorDurationYears")
                        .HasColumnType("double precision");

                    b.Property<double>("StdErrorTotalYieldYear")
                        .HasColumnType("double precision");

                    b.Property<string>("TotalYieldYearDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CalculatedAt");

                    b.ToTable("BondMetrics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
